import 'package:get/get_utils/get_utils.dart';

class Strings {
  ///-----------------------introScreen-------------------------------------------
  static String introPage1Title = "introPage1Title".tr;
  static String introPage1Subitle = "introPage1Subtitle".tr;
  static String introPage2Title = "introPage2Title".tr;
  static String introPage2Subitle = "introPage2Subtitle".tr;
  static String introPage3Title = "introPage3Title".tr;
  static String introPage3Subitle = "introPage3Subtitle".tr;

  static String introPage1TitleM = "introPage1TitleM".tr;
  static String introPage1SubitleM = "introPage1SubtitleM".tr;
  static String introPage2TitleM = "introPage2TitleM".tr;
  static String introPage2SubitleM = "introPage2SubtitleM".tr;
  static String introPage3TitleM = "introPage3TitleM".tr;
  static String introPage3SubitleM = "introPage3SubtitleM".tr;

  ///-----------------------firstScreen-------------------------------------------
  static String logo = "logo".tr;
  static String jobSeeker = "jobSeeker".tr;

  ///-------------------------sentences--------------------------------------------
  static String firstScreenSentences = "firstScreenSentences".tr;
  static String firstScreenSentencesM = "firstScreenSentencesM".tr;
  static String screenSentences = "screenSentences".tr;

  /// -------------------- Home Page -------------------------- ///

  static String howToFindAPerfectJob = "howToFindAPerfectJob".tr;
  static String tipsForYou = "tipsForYou".tr;
  static String seeAll = "seeAll".tr;
  static String jobRecommendation = "jobRecommendation".tr;
  static String readMore = "readMore".tr;

  /// -------------------- Notification -------------------------- ///
  static String notification = "notification".tr;

  /// -------------------- Job Details -------------------------- ///
  static String jobDetails = "jobDetails".tr;
  static String requirements = "requirements".tr;
  static String applyNow = "applyNow".tr;
  static String apply = "apply".tr;
  static String uploadResume = "uploadResume".tr;
  static String uploadYourCvOr = "uploadYourCvOr".tr;
  static String uploading = "uploading".tr;
  static String successful = "successful".tr;
  static String failed = "failed".tr;
  static String youHaveSuccessfullyApplied = "youHaveSuccessfullyApplied".tr;
  static String seeAppliedJobsList = "seeAppliedJobsList".tr;
  static String gotoApplications = "gotoApplications".tr;
  static String discoverMoreJobs = "discoverMoreJobs".tr;
  static String postAnotherVacancy = "postAnotherVacancy".tr;
  static String backToHome = "backToHome".tr;
  static String tryAgain = "tryAgain".tr;
  static String ok = "ok".tr;
  static String settings = "settings".tr;
  static String security = "security".tr;
  static String appearance = "appearance".tr;
  static String localization = 'localization'.tr;

  static String help = "help".tr;
  static String logout = "logout".tr;
  static String sound = "sound".tr;
  static String vibrate = "vibrate".tr;
  static String newTipsAvailable = "newTipsAvailable".tr;
  static String newServiceAvailable = "newServiceAvailable".tr;
  static String pleaseMakeSureThatYourInternet =
      "pleaseMakeSureThatYourInternet".tr;
  static String pleaseMakeSureThatYour = "pleaseMakeSureThatYour".tr;
  static String uIUXDesigner = "uIUXDesigner".tr;
  static String airBNB = "airBNB".tr;
  static String welcome = 'welcome'.tr;
  static String hello = 'hello'.tr;

  // ignore: constant_identifier_names
  static String recentPeopleApplication = "recentPeopleApplication".tr;
  static String nowYouCanSeeAllTheApplier = "nowYouCanSeeAllTheApplier".tr;
  static String applicants = "applicants".tr;
  static String seeResume = "seeResume".tr;
  static String markStatusAs = "markStatusAs".tr;
  static String message = "message".tr;
  static String sendToApplicants = "sendToApplicants".tr;
  static String signUpForFree = "signUpForFree".tr;
  static String signIn = "signIn".tr;
  static String alreadyHaveAccount = "alreadyHaveAccount".tr;
  static String google = "google".tr;
  static String facebook = "facebook".tr;
  static String orContinueWith = "orContinueWith".tr;
  static String rememberMe = "rememberMe".tr;
  static String country = "country".tr;
  static String password = "password".tr;
  static String phoneNumber = "phoneNumber".tr;
  static String email = "email".tr;
  static String firstName = "firstName".tr;
  static String lastName = "lastName".tr;
  static String occupation = "occupation".tr;
  static String city = "city".tr;
  static String state = "state".tr;
  static String signUp = "signUp".tr;
  static String signInToYourAccount = "signInToYourAccount".tr;
  static String forgotThePassword = "forgotThePassword".tr;
  static String donTHaveAccount = "donTHaveAccount".tr;
  static String resetPassword = "resetPassword".tr;
  static String createANewPassword = "createANewPassword".tr;
  static String newPassword = "newPassword".tr;
  static String confirmNewPassword = 'confirmNewPassword'.tr;
  static String save = "save".tr;
  static String forgotPassword = "forgotPassword".tr;
  static String codeHasBeen = "codeHasBeen".tr;
  static String invalidOTPCode = "invalidOTPCode".tr;
  static String resendCodeIn = "resendCodeIn".tr;
  static String verify = "verify".tr;
  static String joiningInterview = "joiningInterview".tr;
  static String chatBox = 'chatBox'.tr;
  static String online = "online";
  static String createVacancies = "createVacancies".tr;
  static String openPosition = "openPosition".tr;
  static String salary = "salary".tr;
  static String location = "location".tr;
  static String type = "type".tr;
  static String category = "category".tr;
  static String status = "status".tr;
  static String next = "next".tr;
  static String profile = "profile".tr;
  static String cancel = "cancel".tr;
  static String exit = "exit".tr;
  static String createAccount = "createAccount".tr;
  static String termsOfService = "termsOfService".tr;
  static String registerForFree = "registerForFree".tr;
  static String login = "login".tr;
  static String fullName = "fullName".tr;
  static String dateOfBirth = "dateOfBirth".tr;
  static String address = "address".tr;
  static String edit = "edit".tr;
  static String savedJobs = "savedJobs".tr;
  static String searchJobs = "searchJobs".tr;
  static String yourMostRecentSearches = "yourMostRecentSearches".tr;
  static String seeDetails = "seeDetails".tr;
  static String name = "name".tr;
  static String back = "back".tr;
  static String home = "home".tr;
  static String applies = "applies".tr;
  static String inbox = "inbox".tr;
  static String organizationProfile = "organizationProfile".tr;
  static String uploadCompanyLogo = "uploadCompanyLogo".tr;
  static String nameOfCompany = "nameOfCompany".tr;
  static String companyEmail = "companyEmail".tr;
  static String establishedDate = "establishedDate".tr;
  static String companyAddress = "companyAddress".tr;
  static String confirm = "confirm".tr;
  static String updateVacancy = "updateVacancy".tr;
  static String addNewRequirements = "addNewRequirements".tr;
  static String jobVacancyPosted = "jobVacancyPosted".tr;
  static String oopsFailedToPost = "oopsFailedToPost".tr;
  static String applications = "applications".tr;
  static String empty = "empty".tr;
  static String updateVacancies = "updateVacancies".tr;
  static String searchJobsHere = "searchJobsHere".tr;
  static String viewAll = "viewAll".tr;
  static String whatAreYouLookingFor = "whatAreYouLookingFor".tr;
  static String postJobVacancy = "postJobVacancy".tr;
  static String oopsFailed = "oopsFailed".tr;
  static String darkMode = "darkMode".tr;
  static String enterValidOccupation = "enterValidOccupation".tr;
  static String enterValidAddress = "enterValidAddress".tr;
  static String enterValidEmail = "enterValidEmail".tr;
  static String enterValidName = "enterValidName".tr;
  static String congrats = "congrats".tr;
  static String gotoHomePage = "gotoHomePage".tr;
  static String chooseLanguage = "chooseLanguage".tr;
  static String hindi = "hindi".tr;
  static String english = "english".tr;
  static String spanish = "spanish".tr;
  static String arabic = "arabic".tr;
  static String addRequirements = "addRequirements".tr;
  static String applicationAccepted = "applicationAccepted".tr;
  static String sendMessageToRecruiterNow = "sendMessageToRecruiterNow".tr;
  static String applicationPending = "applicationPending".tr;
  static String waitingForReview = "waitingForReview".tr;
  static String applicationRejected = "applicationRejected".tr;
  static String discoverAnotherJob = "DiscoverAnotherJob".tr;
  static String doYouWantToExit = "doYouWantToExit".tr;
  static String getStarted = "getStarted".tr;
  static String allJob = "allJob".tr;
  static String writer = "writer".tr;
  static String design = "design".tr;
  static String finance = "finance".tr;
  static String software = "software".tr;
  static String databaseManager = "databaseManager".tr;
  static String productManager = "productManager".tr;
  static String fullStackDeveloper = "fullStackDeveloper".tr;
  static String dataScientist = "dataScientist".tr;
  static String webDevelopers = "webDevelopers".tr;
  static String networking = "networking".tr;
  static String cyberSecurity = "cyberSecurity".tr;
  static String allChat = "allChat".tr;
  static String unread = "unread".tr;
  static String archived = "archived".tr;
  static String accepted = "accepted".tr;
  static String interview = "interview".tr;
  static String rejected = "rejected".tr;
  static String sent = "sent".tr;
  static String all = "all".tr;
  static String pleaseEnterEmail = 'pleaseEnterEmail'.tr;
  static String invalidEmail = 'invalidEmail'.tr;
  static String pleaseEnterFirstname = "pleaseEnterFirstname".tr;
  static String pleaseEnterLastname = "pleaseEnterLastname".tr;
  static String pleaseEnterCity = "pleaseEnterCity".tr;
  static String pleaseEnterState = "pleaseEnterState".tr;
  static String pleaseEnterCountry = "pleaseEnterCountry".tr;
  static String pleaseEnterPhoneNumber = "pleaseEnterPhoneNumber".tr;
  static String india = "india".tr;
  static String unitedStates = "unitedStates".tr;
  static String europe = "europe".tr;
  static String unitedKingdom = "unitedKingdom".tr;
  static String cuba = "cuba".tr;
  static String havana = "havana".tr;
  static String cyprus = "cyprus".tr;
  static String nicosia = "nicosia".tr;
  static String czech = "czech".tr;
  static String republic = "republic".tr;
  static String prague = "prague".tr;
  static String skip = "skip".tr;
  static String register = "register".tr;
  static String createVacanciesNow = "createVacanciesNow".tr;
  static String allVacancies = "allVacancies".tr;
  static String active = "active".tr;
  static String inactive = "inactive".tr;
  static String partTime = "partTime".tr;
  static String freelancer = "freelancer".tr;
  static String remote = "remote".tr;
  static String fullTime = "fullTime".tr;

  static String pleaseEnterPosition = "pleaseEnterPosition".tr;
  static String pleaseEnterSalary = "pleaseEnterSalary".tr;
  static String pleaseEnterLocation = "pleaseEnterLocation".tr;
  static String pleaseEnterType = "pleaseEnterType".tr;
  static String pleaseEnterCategory = "pleaseEnterCategory".tr;
  static String pleaseEnterStatus = "pleaseEnterStatus".tr;

  static String pleaseEnterCompanyName = "pleaseEnterCompanyName".tr;
  static String pleaseEnterCompanyEmail = "pleaseEnterCompanyEmail".tr;
  static String pleaseEnterDate = "pleaseEnterDate".tr;
  static String pleaseEnterAddress = "pleaseEnterAddress".tr;

  static String scheduleInterview = "scheduleInterview".tr;
  static String pleaseEnterDesignationCompanies =
      "pleaseEnterDesignationCompanies".tr;
  static String findYourDreamJob = "findYourDreamJob".tr;
  static String formGallery = "formGallery".tr;
  static String takePhoto = "takePhoto".tr;
  static String editProfile = "editProfile".tr;
  static String saveChanges = "saveChanges".tr;
  static String areYouSureYouWantToSignOut = "areYouSureYouWantToSignOut".tr;
}
